=== S8-stack/S8-core-web-helium/config/server/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://s8.com"
 xmlns:tns="http://s8.com"
 elementFormDefault="qualified">
	<xs:element name="SSL_WebConfiguration" type="tns:com.s8.io.web.ssl.SSL_WebConfiguration"/>

	<xs:complexType name="com.s8.io.web.ssl.SSL_WebConfiguration">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="isServer" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSL-keystore_pathname" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSL-keystore_password" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSL-encryption_protocol" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="timeout" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSL-maxPacketSize" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="backlog" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="port" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="socket_RxSocketConfiguration" type="tns:com.s8.io.web.rx.RxSocketConfiguration" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSL-isVerbose" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="host" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="RxSocketConfiguration" type="tns:com.s8.io.web.rx.RxSocketConfiguration" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="isRxVerbose" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="socket" type="tns:com.s8.io.web.rx.RxSocketConfiguration" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="com.s8.io.web.rx.RxSocketConfiguration">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="receive-buffer-size" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="keep-alive" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="traffic-class" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="send-buffer-size" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="OOBINLINE" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="TCP_NODELAY" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== S8-stack/S8-core-web-helium/config/ssl/client_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<SSL_WebConfiguration xmlns="http://s8.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://s8.com schema.xsd">
	<name>client</name>
	<isServer>false</isServer>
	<port>1336</port>
	<host>localhost</host>
	<SSL-isVerbose>true</SSL-isVerbose>
	<SSL-encryption_protocol>TLSv1.3</SSL-encryption_protocol>
	<SSL-keystore_pathname>config/s2/keystore.jks</SSL-keystore_pathname>
	<SSL-keystore_password>rDfe4_!xef</SSL-keystore_password>
</SSL_WebConfiguration>

=== S8-stack/S8-core-web-helium/config/ssl/server_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<SSL_WebConfiguration xmlns="http://s8.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://s8.com schema.xsd">
	<name>server</name>
	<isServer>true</isServer>
	<port>1336</port>
	<SSL-encryption_protocol>TLSv1.3</SSL-encryption_protocol>
	<SSL-keystore_pathname>config/s2/keystore.jks</SSL-keystore_pathname>
	<SSL-keystore_password>rDfe4_!xef</SSL-keystore_password>
	<SSL-isVerbose>true</SSL-isVerbose>
</SSL_WebConfiguration>
